### PR TITLE
Adapt queries to also handle "no grouping" case

### PR DESCRIPTION
**Pull request by lokal-profil**
Bug: [T237182](https://phabricator.wikimedia.org/T237182)

### CODE REVIEW

**Comment by lokal-profil** [comment]
sorry for the many commits, local testing broken again

**Comment by JeanFred** [comment]
Thanks for this!

Would you mind extracting the unit-tests for the existing functionality in its own PR?

**Comment by lokal-profil** [comment]
> Thanks for this!
> 
> Would you mind extracting the unit-tests for the existing functionality in its own PR?

#7

**Comment by JeanFred** [comment]
> > Thanks for this!
> > Would you mind extracting the unit-tests for the existing functionality in its own PR?
> 
> #7

Cheers, now merged :) Could you rebase that one?

**Comment by lokal-profil** [comment]
@JeanFred On my phone for a week, don't think its up to the task.

**Comment by lokal-profil** [comment]
Sudden hessitation. What I assumed in this patch is that "no grouping" = "does not have a value for the grouping property". 
If "no grouping" is instead all entries "without the grouping property" + where there were less than grouping_threshold occurrences of the grouping property value, then my suggested query is incorrect and something much more complicated is needed.

**Comment by lokal-profil** [comment]
@JeanFred which interpretation is the correct one here?

**Comment by lokal-profil** [comment]
Looking at https://www.wikidata.org/w/index.php?title=User:Lokal_Profil/Arbetsam_dashboard&oldid=1050387390 (comparing the total with the sum of the rows) I think my first interpretation was correct in which case this patch should work.

**Comment by lokal-profil** [comment]
@JeanFred Is there anything left ot do here?

**Comment by JeanFred** [comment]
> @JeanFred Is there anything left ot do here?

Not really − Following your sudden hesitation, I wanted to investigate myself but did not get around doing it ^_^"

**Comment by lokal-profil** [comment]
> > @JeanFred Is there anything left ot do here?
> 
> Not really − Following your sudden hesitation, I wanted to investigate myself but did not get around doing it ^_^"

Then it's good to go. I found a much simpler table which convinced me that the original interpretation was correct.

**Review by JeanFred — APPROVED** [review]

**Comment by JeanFred** [comment]
Sorry for the lag, now merged. Thanks for the contribution!

**Pull request merged**
